<?php 
/* 
 * This file is part of a copyrighted work; it is distributed with NO WARRANTY.
 * See the file COPYRIGHT.html for more details.
 * 
 * DDC Classification Topic Mapping (Level 3)
 * Source: Wikipedia - Dewey Decimal Classification
 * https://en.wikipedia.org/wiki/List_of_Dewey_Decimal_classes
 *
 * This file references materials licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License.
 * License details: https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * -- F. Tumulak
 */
$updateSQL = "
UPDATE extract_ddc
SET classification_adv = CASE
  -- General Works
  WHEN LEFT(ddc, 3) = '000' THEN 'Computer science, information and general works'
  WHEN LEFT(ddc, 3) = '001' THEN 'Knowledge'
  WHEN LEFT(ddc, 3) = '002' THEN 'The book (writing, libraries, and book-related topics)'
  WHEN LEFT(ddc, 3) = '003' THEN 'Systems'
  WHEN LEFT(ddc, 3) = '004' THEN 'Data processing and computer science'
  WHEN LEFT(ddc, 3) = '005' THEN 'Computer programming, programs, and data'
  WHEN LEFT(ddc, 3) = '006' THEN 'Special computer methods (e.g. AI, multimedia, VR)'
  WHEN LEFT(ddc, 3) BETWEEN '007' AND '009' THEN 'Unassigned (000s)'
  WHEN LEFT(ddc, 3) = '010' THEN 'Bibliography'
  WHEN LEFT(ddc, 3) = '011' THEN 'Bibliographies'
  WHEN LEFT(ddc, 3) = '012' THEN 'Bibliographies of individuals'
  WHEN LEFT(ddc, 3) = '013' THEN 'Unassigned'
  WHEN LEFT(ddc, 3) = '014' THEN 'Bibliographies of anonymous and pseudonymous works'
  WHEN LEFT(ddc, 3) = '015' THEN 'Bibliographies of works from specific places'
  WHEN LEFT(ddc, 3) = '016' THEN 'Bibliographies of works on specific subjects'
  WHEN LEFT(ddc, 3) = '017' THEN 'General subject catalogs'
  WHEN LEFT(ddc, 3) = '018' THEN 'Catalogs arranged by author, date, etc.'
  WHEN LEFT(ddc, 3) = '019' THEN 'Dictionary catalogs'
  WHEN LEFT(ddc, 3) = '020' THEN 'Library and information sciences'
  WHEN LEFT(ddc, 3) = '021' THEN 'Library relationships (with archives, information centers, etc.)'
  WHEN LEFT(ddc, 3) = '022' THEN 'Administration of physical plant'
  WHEN LEFT(ddc, 3) = '023' THEN 'Personnel management'
  WHEN LEFT(ddc, 3) = '024' THEN 'Unassigned'
  WHEN LEFT(ddc, 3) = '025' THEN 'Library operations'
  WHEN LEFT(ddc, 3) = '026' THEN 'Libraries for specific subjects'
  WHEN LEFT(ddc, 3) = '027' THEN 'General libraries'
  WHEN LEFT(ddc, 3) = '028' THEN 'Reading and use of other information media'
  WHEN LEFT(ddc, 3) = '029' THEN 'Unassigned'
  WHEN LEFT(ddc, 3) = '030' THEN 'General encyclopedic works'
  WHEN LEFT(ddc, 3) = '031' THEN 'Encyclopedias in American English'
  WHEN LEFT(ddc, 3) = '032' THEN 'Encyclopedias in English'
  WHEN LEFT(ddc, 3) = '033' THEN 'Encyclopedias in other Germanic languages'
  WHEN LEFT(ddc, 3) = '034' THEN 'Encyclopedias in French, Occitan, and Catalan'
  WHEN LEFT(ddc, 3) = '035' THEN 'Encyclopedias in Italian, Romanian, and related languages'
  WHEN LEFT(ddc, 3) = '036' THEN 'Encyclopedias in Spanish and Portuguese'
  WHEN LEFT(ddc, 3) = '037' THEN 'Encyclopedias in Slavic languages'
  WHEN LEFT(ddc, 3) = '038' THEN 'Encyclopedias in Scandinavian languages'
  WHEN LEFT(ddc, 3) = '039' THEN 'Encyclopedias in other languages'
  WHEN LEFT(ddc, 3) BETWEEN '040' AND '049' THEN 'Unassigned (040s)'
  WHEN LEFT(ddc, 3) = '050' THEN 'Magazines, journals and serials'
  WHEN LEFT(ddc, 3) = '051' THEN 'Serials in American English'
  WHEN LEFT(ddc, 3) = '052' THEN 'Serials in English'
  WHEN LEFT(ddc, 3) = '053' THEN 'Serials in other Germanic languages'
  WHEN LEFT(ddc, 3) = '054' THEN 'Serials in French, Occitan, Catalan'
  WHEN LEFT(ddc, 3) = '055' THEN 'Serials in Italian, Romanian, and related languages'
  WHEN LEFT(ddc, 3) = '056' THEN 'Serials in Spanish and Portuguese'
  WHEN LEFT(ddc, 3) = '057' THEN 'Serials in Slavic languages'
  WHEN LEFT(ddc, 3) = '058' THEN 'Serials in Scandinavian languages'
  WHEN LEFT(ddc, 3) = '059' THEN 'Serials in other languages'
  WHEN LEFT(ddc, 3) = '060' THEN 'Associations, organizations and museums'
  WHEN LEFT(ddc, 3) BETWEEN '061' AND '069' THEN 'Specific associations, organizations, museum science'
  WHEN LEFT(ddc, 3) = '070' THEN 'News media, journalism, and publishing'
  WHEN LEFT(ddc, 3) BETWEEN '071' AND '079' THEN 'Regional newspapers and publishing categories'
  WHEN LEFT(ddc, 3) = '080' THEN 'Quotations – General collections'
  WHEN LEFT(ddc, 3) BETWEEN '081' AND '089' THEN 'Quotations in various languages'
  WHEN LEFT(ddc, 3) = '090' THEN 'Manuscripts and rare books'
  WHEN LEFT(ddc, 3) BETWEEN '091' AND '099' THEN 'Specific manuscript/rare book categories'
  
  -- Philosophy & Psychology
  WHEN LEFT(ddc, 3) = '100' THEN 'Philosophy and psychology'
  WHEN LEFT(ddc, 3) = '101' THEN 'Theory of philosophy'
  WHEN LEFT(ddc, 3) = '102' THEN 'Miscellany'
  WHEN LEFT(ddc, 3) = '103' THEN 'Dictionaries and encyclopedias of philosophy'
  WHEN LEFT(ddc, 3) = '104' THEN 'Unassigned - formerly Essays'
  WHEN LEFT(ddc, 3) = '105' THEN 'Serial publications'
  WHEN LEFT(ddc, 3) = '106' THEN 'Organizations and management'
  WHEN LEFT(ddc, 3) = '107' THEN 'Education, research, related topics of philosophy'
  WHEN LEFT(ddc, 3) = '108' THEN 'Groups of people'
  WHEN LEFT(ddc, 3) = '109' THEN 'History and collected biography'
  
  WHEN LEFT(ddc, 3) = '110' THEN 'Metaphysics'
  WHEN LEFT(ddc, 3) = '111' THEN 'Ontology'
	WHEN LEFT(ddc, 3) = '112' THEN 'Unassigned — formerly Methodology'
	WHEN LEFT(ddc, 3) = '113' THEN 'Cosmology (Philosophy of nature)'
	WHEN LEFT(ddc, 3) = '114' THEN 'Space'
	WHEN LEFT(ddc, 3) = '115' THEN 'Time'
	WHEN LEFT(ddc, 3) = '116' THEN 'Change'
	WHEN LEFT(ddc, 3) = '117' THEN 'Force and energy'
	WHEN LEFT(ddc, 3) = '118' THEN 'Cosmology (Philosophy of nature)'
	WHEN LEFT(ddc, 3) = '119' THEN 'Number and quantity'
	
	WHEN LEFT(ddc, 3) = '120' THEN 'Epistemology, causation, and humankind'
	WHEN LEFT(ddc, 3) = '121' THEN 'Epistemology (Theory of knowledge)'
	WHEN LEFT(ddc, 3) = '122' THEN 'Causation'
	WHEN LEFT(ddc, 3) = '123' THEN 'Determinism and indeterminism'
	WHEN LEFT(ddc, 3) = '124' THEN 'Teleology'
	WHEN LEFT(ddc, 3) = '125' THEN 'Unassigned — formerly Infinity'
	WHEN LEFT(ddc, 3) = '126' THEN 'The self'
	WHEN LEFT(ddc, 3) = '127' THEN 'The unconscious and the subconscious'
	WHEN LEFT(ddc, 3) = '128' THEN 'Humankind'
	WHEN LEFT(ddc, 3) = '129' THEN 'Origin and destiny of individual souls'
	
	WHEN LEFT(ddc, 3) = '130' THEN 'Parapsychology and occultism'
	WHEN LEFT(ddc, 3) = '131' THEN 'Parapsychological and occult methods'
	WHEN LEFT(ddc, 3) = '132' THEN 'Unassigned — formerly Mental derangements'
	WHEN LEFT(ddc, 3) = '133' THEN 'Specific topics in parapsychology and occultism'
	WHEN LEFT(ddc, 3) = '134' THEN 'Unassigned — formerly Mesmerism and Clairvoyance'
	WHEN LEFT(ddc, 3) = '135' THEN 'Dreams and mysteries'
	WHEN LEFT(ddc, 3) = '136' THEN 'Unassigned — formerly Mental characteristics'
	WHEN LEFT(ddc, 3) = '137' THEN 'Divinatory graphology'
	WHEN LEFT(ddc, 3) = '138' THEN 'Physiognomy'
	WHEN LEFT(ddc, 3) = '139' THEN 'Phrenology'
	
	WHEN LEFT(ddc, 3) = '140' THEN 'Specific philosophical schools and viewpoints'
	WHEN LEFT(ddc, 3) = '141' THEN 'Idealism and related systems and doctrines'
	WHEN LEFT(ddc, 3) = '142' THEN 'Critical philosophy'
	WHEN LEFT(ddc, 3) = '143' THEN 'Bergsonism and intuitionism'
	WHEN LEFT(ddc, 3) = '144' THEN 'Humanism and related systems and doctrines'
	WHEN LEFT(ddc, 3) = '145' THEN 'Sensationalism'
	WHEN LEFT(ddc, 3) = '146' THEN 'Naturalism and related systems and doctrines'
	WHEN LEFT(ddc, 3) = '147' THEN 'Pantheism and related systems and doctrines'
	WHEN LEFT(ddc, 3) = '148' THEN 'Dogmatism, eclecticism, liberalism, syncretism, and traditionalism'
	WHEN LEFT(ddc, 3) = '149' THEN 'Other philosophical systems and doctrines'

	WHEN LEFT(ddc, 3) = '150' THEN 'Psychology'	
	WHEN LEFT(ddc, 3) = '151' THEN 'Unassigned — formerly Intellect'	
	WHEN LEFT(ddc, 3) = '152' THEN 'Sensory perception, movement, emotions, and physiological drives'
	WHEN LEFT(ddc, 3) = '153' THEN 'Conscious mental processes and intelligence'
	WHEN LEFT(ddc, 3) = '154' THEN 'Subconscious and altered states and processes'
	WHEN LEFT(ddc, 3) = '155' THEN 'Differential and developmental psychology'
	WHEN LEFT(ddc, 3) = '156' THEN 'Comparative psychology'
	WHEN LEFT(ddc, 3) = '157' THEN 'Unassigned — formerly Emotions'
	WHEN LEFT(ddc, 3) = '158' THEN 'Applied psychology'
	WHEN LEFT(ddc, 3) = '159' THEN 'Unassigned — formerly Will'
	
	WHEN LEFT(ddc, 3) = '160' THEN 'Philosophical logic'
	WHEN LEFT(ddc, 3) = '161' THEN 'Induction'
	WHEN LEFT(ddc, 3) = '162' THEN 'Deduction'
  WHEN LEFT(ddc, 3) BETWEEN '163' AND '164' THEN 'Unassigned (160s)'
	WHEN LEFT(ddc, 3) = '165' THEN 'Fallacies and sources of error'
	WHEN LEFT(ddc, 3) = '166' THEN 'Syllogisms'
	WHEN LEFT(ddc, 3) = '167' THEN 'Hypotheses'
	WHEN LEFT(ddc, 3) = '168' THEN 'Argument and persuasion'
	WHEN LEFT(ddc, 3) = '169' THEN 'Analogy'

	WHEN LEFT(ddc, 3) = '170' THEN 'Ethics (Moral philosophy)'	
	WHEN LEFT(ddc, 3) = '171' THEN 'Ethical systems'		
	WHEN LEFT(ddc, 3) = '172' THEN 'Political ethics'	
	WHEN LEFT(ddc, 3) = '173' THEN 'Ethics of family relationships'	
	WHEN LEFT(ddc, 3) = '174' THEN 'Occupational ethics'	
	WHEN LEFT(ddc, 3) = '175' THEN 'Ethics of recreation, leisure, public performances, communication'	
	WHEN LEFT(ddc, 3) = '176' THEN 'Ethics of sex and reproduction'	
	WHEN LEFT(ddc, 3) = '177' THEN 'Ethics of social relations'	
	WHEN LEFT(ddc, 3) = '178' THEN 'Ethics of consumption'	
	WHEN LEFT(ddc, 3) = '179' THEN 'Other ethical norms'	
	
	WHEN LEFT(ddc, 3) = '180' THEN 'Ancient, medieval, eastern philosophy'
	WHEN LEFT(ddc, 3) = '181' THEN 'Eastern philosophy'
	WHEN LEFT(ddc, 3) = '182' THEN 'Pre-Socratic Greek philosophies'
	WHEN LEFT(ddc, 3) = '183' THEN 'Sophistic, Socratic, related Greek philosophies'
	WHEN LEFT(ddc, 3) = '184' THEN 'Platonic philosophy'
	WHEN LEFT(ddc, 3) = '185' THEN 'Aristotelian philosophy'
	WHEN LEFT(ddc, 3) = '186' THEN 'Skeptic and Neoplatonic philosophies'
	WHEN LEFT(ddc, 3) = '187' THEN 'Epicurean philosophy'
	WHEN LEFT(ddc, 3) = '188' THEN 'Stoic philosophy'
	WHEN LEFT(ddc, 3) = '189' THEN 'Medieval Western philosophy'

	WHEN LEFT(ddc, 3) = '190' THEN 'Modern Western and other noneastern philosophy'
	WHEN LEFT(ddc, 3) = '191' THEN 'Philosophy of the United States and Canada'
	WHEN LEFT(ddc, 3) = '192' THEN 'Philosophy of the British Isles'
	WHEN LEFT(ddc, 3) = '193' THEN 'Philosophy of Germany and Austria'
	WHEN LEFT(ddc, 3) = '194' THEN 'Philosophy of France'
	WHEN LEFT(ddc, 3) = '195' THEN 'Philosophy of Italy'
	WHEN LEFT(ddc, 3) = '196' THEN 'Philosophy of Spain and Portugal'
	WHEN LEFT(ddc, 3) = '197' THEN 'Philosophy of Russia'
	WHEN LEFT(ddc, 3) = '198' THEN 'Philosophy of Scandinavia and Finland'
	WHEN LEFT(ddc, 3) = '199' THEN 'Philosophy in other geographic areas'
	
	-- Religion
	WHEN LEFT(ddc, 3) = '200' THEN 'Religion'
	WHEN LEFT(ddc, 3) = '201' THEN 'Religious mythology, general classes of religion, interreligious relations and attitudes'
	WHEN LEFT(ddc, 3) = '202' THEN 'Doctrines'
	WHEN LEFT(ddc, 3) = '203' THEN 'Public worship and other practices'
	WHEN LEFT(ddc, 3) = '204' THEN 'Religious experience, life, practice'
	WHEN LEFT(ddc, 3) = '205' THEN 'Religious ethics'
	WHEN LEFT(ddc, 3) = '206' THEN 'Leaders and organization'
	WHEN LEFT(ddc, 3) = '207' THEN 'Missions and religious education'
	WHEN LEFT(ddc, 3) = '208' THEN 'Sources'
	WHEN LEFT(ddc, 3) = '209' THEN 'Sects and reform movements'

	WHEN LEFT(ddc, 3) = '210' THEN 'Philosophy and theory of religion'
	WHEN LEFT(ddc, 3) = '211' THEN 'Concepts of God'
	WHEN LEFT(ddc, 3) = '212' THEN 'Existence, ways of knowing God, attributes of God'
	WHEN LEFT(ddc, 3) = '213' THEN 'Creation'
	WHEN LEFT(ddc, 3) = '214' THEN 'Theodicy'
	WHEN LEFT(ddc, 3) = '215' THEN 'Science and religion'
	WHEN LEFT(ddc, 3) = '216' THEN 'Unassigned — formerly Evil'
	WHEN LEFT(ddc, 3) = '217' THEN 'Unassigned — formerly Prayer'
	WHEN LEFT(ddc, 3) = '218' THEN 'Humankind'
	WHEN LEFT(ddc, 3) = '219' THEN 'Unassigned — formerly Analogies'

	WHEN LEFT(ddc, 3) = '220' THEN 'Bible'
	WHEN LEFT(ddc, 3) = '221' THEN 'Old Testament (Tanakh)'
	WHEN LEFT(ddc, 3) = '222' THEN 'Historical books of Old Testament'
	WHEN LEFT(ddc, 3) = '223' THEN 'Poetic books of Old Testament'
	WHEN LEFT(ddc, 3) = '224' THEN 'Prophetic books of Old Testament'
	WHEN LEFT(ddc, 3) = '225' THEN 'New Testament'
	WHEN LEFT(ddc, 3) = '226' THEN 'Gospels and Acts'
	WHEN LEFT(ddc, 3) = '227' THEN 'Epistles'
	WHEN LEFT(ddc, 3) = '228' THEN 'Revelation (Apocalypse)'
	WHEN LEFT(ddc, 3) = '229' THEN 'Apocrypha, pseudepigrapha, and inter-testamental works'

	WHEN LEFT(ddc, 3) = '230' THEN 'Christianity'
	WHEN LEFT(ddc, 3) = '231' THEN 'God'
	WHEN LEFT(ddc, 3) = '232' THEN 'Jesus Christ and his family'
	WHEN LEFT(ddc, 3) = '233' THEN 'Humankind'
	WHEN LEFT(ddc, 3) = '234' THEN 'Salvation and grace'
	WHEN LEFT(ddc, 3) = '235' THEN 'Spiritual beings'
	WHEN LEFT(ddc, 3) = '236' THEN 'Eschatology'
	WHEN LEFT(ddc, 3) = '237' THEN 'Unassigned — formerly Future state'
	WHEN LEFT(ddc, 3) = '238' THEN 'Creeds, confessions of faith, covenants, and catechisms'
	WHEN LEFT(ddc, 3) = '239' THEN 'Apologetics and polemics'

	WHEN LEFT(ddc, 3) = '240' THEN 'Christian moral and devotional theology'
	WHEN LEFT(ddc, 3) = '241' THEN 'Christian ethics'
	WHEN LEFT(ddc, 3) = '242' THEN 'Devotional literature'
	WHEN LEFT(ddc, 3) = '243' THEN 'Evangelistic writings for individuals and families'
	WHEN LEFT(ddc, 3) = '244' THEN 'Unassigned — formerly Religious fiction'
	WHEN LEFT(ddc, 3) = '245' THEN 'Unassigned — formerly Hymnology'
	WHEN LEFT(ddc, 3) = '246' THEN 'Use of art in Christianity'
	WHEN LEFT(ddc, 3) = '247' THEN 'Church furnishings and related articles'
	WHEN LEFT(ddc, 3) = '248' THEN 'Christian experience, practice, life'
	WHEN LEFT(ddc, 3) = '249' THEN 'Christian observances in family life'

	WHEN LEFT(ddc, 3) = '250' THEN 'Local Christian church and Christian religious orders'
	WHEN LEFT(ddc, 3) = '251' THEN 'Preaching (Homiletics)'
	WHEN LEFT(ddc, 3) = '252' THEN 'Texts of sermons'
	WHEN LEFT(ddc, 3) = '253' THEN 'Pastoral office and work (Pastoral theology)'
	WHEN LEFT(ddc, 3) = '254' THEN 'Parish administration'
	WHEN LEFT(ddc, 3) = '255' THEN 'Religious congregations and orders'
	WHEN LEFT(ddc, 3) = '256' THEN 'Unassigned — formerly Religious societies'
	WHEN LEFT(ddc, 3) = '257' THEN 'Unassigned — formerly Parochial schools, libraries, etc.'
	WHEN LEFT(ddc, 3) = '258' THEN 'Unassigned — formerly Parochial medicine'
	WHEN LEFT(ddc, 3) = '259' THEN 'Pastoral care of families, of specific groups of people'

	WHEN LEFT(ddc, 3) = '260' THEN 'Christian social and ecclesiastical theology'
	WHEN LEFT(ddc, 3) = '261' THEN 'Social theology and interreligious relations and attitudes'
	WHEN LEFT(ddc, 3) = '262' THEN 'Ecclesiology'
	WHEN LEFT(ddc, 3) = '263' THEN 'Days, times, places of religious observance'
	WHEN LEFT(ddc, 3) = '264' THEN 'Public worship'
	WHEN LEFT(ddc, 3) = '265' THEN 'Sacraments, other rites and acts'
	WHEN LEFT(ddc, 3) = '266' THEN 'Missions'
	WHEN LEFT(ddc, 3) = '267' THEN 'Associations for religious work'
	WHEN LEFT(ddc, 3) = '268' THEN 'Religious education'
	WHEN LEFT(ddc, 3) = '269' THEN 'Spiritual renewal'
	
	WHEN LEFT(ddc, 3) = '270' THEN 'History, geographic treatment, biography of Christianity'
	WHEN LEFT(ddc, 3) = '271' THEN 'Religious congregations and orders in church history'
	WHEN LEFT(ddc, 3) = '272' THEN 'Persecutions in church history'
	WHEN LEFT(ddc, 3) = '273' THEN 'Doctrinal controversies and heresies in general church history'
	WHEN LEFT(ddc, 3) = '274' THEN 'Christianity in Europe'
	WHEN LEFT(ddc, 3) = '275' THEN 'Christianity in Asia'
	WHEN LEFT(ddc, 3) = '276' THEN 'Christianity in Africa'
	WHEN LEFT(ddc, 3) = '277' THEN 'Christianity in North America'
	WHEN LEFT(ddc, 3) = '278' THEN 'Christianity in South America'
	WHEN LEFT(ddc, 3) = '279' THEN 'History of Christianity in other areas'

	WHEN LEFT(ddc, 3) = '280' THEN 'Denominations and sects of Christian church'
	WHEN LEFT(ddc, 3) = '281' THEN 'Early church and Eastern churches'
	WHEN LEFT(ddc, 3) = '282' THEN 'Roman Catholic Church'
	WHEN LEFT(ddc, 3) = '283' THEN 'Anglican churches'
	WHEN LEFT(ddc, 3) = '284' THEN 'Protestant denominations of Continental origin (Lutheran, Continental Reformed)'
	WHEN LEFT(ddc, 3) = '285' THEN 'Presbyterian churches, Reformed churches centered in America, Congregational churches'
	WHEN LEFT(ddc, 3) = '286' THEN 'Baptist, Restoration Movement, Adventist churches'
	WHEN LEFT(ddc, 3) = '287' THEN 'Methodist churches; churches related to Methodism'
	WHEN LEFT(ddc, 3) = '288' THEN 'Unassigned — formerly Unitarian'
	WHEN LEFT(ddc, 3) = '289' THEN 'Other denominations and sects'

	WHEN LEFT(ddc, 3) = '290' THEN 'Other religions'
	WHEN LEFT(ddc, 3) = '291' THEN 'Unassigned — formerly Comparative religion'
	WHEN LEFT(ddc, 3) = '292' THEN 'Classical religion (Greek and Roman religion)'
	WHEN LEFT(ddc, 3) = '293' THEN 'Germanic religion'
	WHEN LEFT(ddc, 3) = '294' THEN 'Religions of Indic origin'
	WHEN LEFT(ddc, 3) = '295' THEN 'Zoroastrianism (Mazdaism, Parseeism)'
	WHEN LEFT(ddc, 3) = '296' THEN 'Judaism'
	WHEN LEFT(ddc, 3) = '297' THEN 'Islam, Bábism, and Baháʼí Faith'
	WHEN LEFT(ddc, 3) = '298' THEN 'Unassigned — formerly Mormonism'
	WHEN LEFT(ddc, 3) = '299' THEN 'Religions not provided for elsewhere'

	-- Social Sciences
	WHEN LEFT(ddc, 3) = '300' THEN 'Social sciences'
	WHEN LEFT(ddc, 3) = '301' THEN 'Sociology and anthropology'
	WHEN LEFT(ddc, 3) = '302' THEN 'Social interaction'
	WHEN LEFT(ddc, 3) = '303' THEN 'Social processes'
	WHEN LEFT(ddc, 3) = '304' THEN 'Factors affecting social behavior'
	WHEN LEFT(ddc, 3) = '305' THEN 'Groups of people'
	WHEN LEFT(ddc, 3) = '306' THEN 'Culture and institutions'
	WHEN LEFT(ddc, 3) = '307' THEN 'Communities'
	WHEN LEFT(ddc, 3) = '308' THEN 'Unassigned — formerly Polygraphy'
	WHEN LEFT(ddc, 3) = '309' THEN 'Unassigned — formerly History of sociology'

	WHEN LEFT(ddc, 3) = '310' THEN 'Collections of general statistics'
	WHEN LEFT(ddc, 3) = '311' THEN 'Unassigned — formerly Theory and methods'
	WHEN LEFT(ddc, 3) = '312' THEN 'Unassigned — formerly Population'
	WHEN LEFT(ddc, 3) = '313' THEN 'Unassigned — formerly Special topics'
	WHEN LEFT(ddc, 3) = '314' THEN 'General statistics of Europe'
	WHEN LEFT(ddc, 3) = '315' THEN 'General statistics of Asia'
	WHEN LEFT(ddc, 3) = '316' THEN 'General statistics of Africa'
	WHEN LEFT(ddc, 3) = '317' THEN 'General statistics of North America'
	WHEN LEFT(ddc, 3) = '318' THEN 'General statistics of South America'
	WHEN LEFT(ddc, 3) = '319' THEN 'General statistics of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica'

	WHEN LEFT(ddc, 3) = '320' THEN 'Political science (Politics and government)'
	WHEN LEFT(ddc, 3) = '321' THEN 'Systems of governments and states'
	WHEN LEFT(ddc, 3) = '322' THEN 'Relation of state to organized groups and their members'
	WHEN LEFT(ddc, 3) = '323' THEN 'Civil and political rights'
	WHEN LEFT(ddc, 3) = '324' THEN 'The political process'
	WHEN LEFT(ddc, 3) = '325' THEN 'International migration and colonization'
	WHEN LEFT(ddc, 3) = '326' THEN 'Slavery and emancipation'
	WHEN LEFT(ddc, 3) = '327' THEN 'International relations'
	WHEN LEFT(ddc, 3) = '328' THEN 'The legislative process'
	WHEN LEFT(ddc, 3) = '329' THEN 'Unassigned— formerly Political Parties'

	WHEN LEFT(ddc, 3) = '330' THEN 'Economics'
	WHEN LEFT(ddc, 3) = '331' THEN 'Labor economics'
	WHEN LEFT(ddc, 3) = '332' THEN 'Financial economics'
	WHEN LEFT(ddc, 3) = '333' THEN 'Economics of land and energy'
	WHEN LEFT(ddc, 3) = '334' THEN 'Cooperatives'
	WHEN LEFT(ddc, 3) = '335' THEN 'Socialism and related systems'
	WHEN LEFT(ddc, 3) = '336' THEN 'Public finance'
	WHEN LEFT(ddc, 3) = '337' THEN 'International economics'
	WHEN LEFT(ddc, 3) = '338' THEN 'Production'
	WHEN LEFT(ddc, 3) = '339' THEN 'Macroeconomics and related topics'

	WHEN LEFT(ddc, 3) = '340' THEN 'Law'
	WHEN LEFT(ddc, 3) = '341' THEN 'Law of nations'
	WHEN LEFT(ddc, 3) = '342' THEN 'Constitutional and administrative law'
	WHEN LEFT(ddc, 3) = '343' THEN 'Military, defense, public property, public finance, tax, commerce (trade), industrial law'
	WHEN LEFT(ddc, 3) = '344' THEN 'Labor, social service, education, cultural law'
	WHEN LEFT(ddc, 3) = '345' THEN 'Criminal law'
	WHEN LEFT(ddc, 3) = '346' THEN 'Private law'
	WHEN LEFT(ddc, 3) = '347' THEN 'Procedure and courts'
	WHEN LEFT(ddc, 3) = '348' THEN 'Laws, regulations, cases'
	WHEN LEFT(ddc, 3) = '349' THEN 'Law of specific jurisdictions, areas, socioeconomic regions, regional intergovernmental organizations'

	WHEN LEFT(ddc, 3) = '350' THEN 'Public administration and military science'
	WHEN LEFT(ddc, 3) = '351' THEN 'Public administration'
	WHEN LEFT(ddc, 3) = '352' THEN 'General considerations of public administration'
	WHEN LEFT(ddc, 3) = '353' THEN 'Specific fields of public administration'
	WHEN LEFT(ddc, 3) = '354' THEN 'Public administration of economy and environment'
	WHEN LEFT(ddc, 3) = '355' THEN 'Military science'
	WHEN LEFT(ddc, 3) = '356' THEN 'Foot forces and warfare'
	WHEN LEFT(ddc, 3) = '357' THEN 'Mounted forces and warfare'
	WHEN LEFT(ddc, 3) = '358' THEN 'Air and other specialized forces and warfare; engineering and related services'
	WHEN LEFT(ddc, 3) = '359' THEN 'Sea forces and warfare'

	WHEN LEFT(ddc, 3) = '360' THEN 'Social problems and services; associations'
	WHEN LEFT(ddc, 3) = '361' THEN 'Social problems and services'
	WHEN LEFT(ddc, 3) = '362' THEN 'Social problems of and services to groups of people'
	WHEN LEFT(ddc, 3) = '363' THEN 'Other social problems and services'
	WHEN LEFT(ddc, 3) = '364' THEN 'Criminology'
	WHEN LEFT(ddc, 3) = '365' THEN 'Penal and related institutions'
	WHEN LEFT(ddc, 3) = '366' THEN 'Secret associations and societies'
	WHEN LEFT(ddc, 3) = '367' THEN 'General clubs'
	WHEN LEFT(ddc, 3) = '368' THEN 'Insurance'
	WHEN LEFT(ddc, 3) = '369' THEN 'Associations'

	WHEN LEFT(ddc, 3) = '370' THEN 'Education'
	WHEN LEFT(ddc, 3) = '371' THEN 'Schools and their activities, special education'
	WHEN LEFT(ddc, 3) = '372' THEN 'Primary education (elementary education)'
	WHEN LEFT(ddc, 3) = '373' THEN 'Secondary education'
	WHEN LEFT(ddc, 3) = '374' THEN 'Adult education'
	WHEN LEFT(ddc, 3) = '375' THEN 'Curriculum'
	WHEN LEFT(ddc, 3) = '376' THEN 'Unassigned — formerly Education of women'
	WHEN LEFT(ddc, 3) = '377' THEN 'Unassigned — formerly Ethical education'
	WHEN LEFT(ddc, 3) = '378' THEN 'Higher education (Tertiary education)'
	WHEN LEFT(ddc, 3) = '379' THEN 'Public policy issues in education'

	WHEN LEFT(ddc, 3) = '380' THEN 'Commerce, communications transportation'
	WHEN LEFT(ddc, 3) = '381' THEN 'Commerce (Trade)'
	WHEN LEFT(ddc, 3) = '382' THEN 'International commerce (Foreign trade)'
	WHEN LEFT(ddc, 3) = '383' THEN 'Postal communication'
	WHEN LEFT(ddc, 3) = '384' THEN 'Communications'
	WHEN LEFT(ddc, 3) = '385' THEN 'Railroad transportation'
	WHEN LEFT(ddc, 3) = '386' THEN 'Inland waterway and ferry transportation'
	WHEN LEFT(ddc, 3) = '387' THEN 'Water, air, space transportation'
	WHEN LEFT(ddc, 3) = '388' THEN 'Transportation'
	WHEN LEFT(ddc, 3) = '389' THEN 'Metrology and standardization'

	WHEN LEFT(ddc, 3) = '390' THEN 'Customs, etiquette, folklore'
	WHEN LEFT(ddc, 3) = '391' THEN 'Costume and personal appearance'
	WHEN LEFT(ddc, 3) = '392' THEN 'Customs of life cycle and domestic life'
	WHEN LEFT(ddc, 3) = '393' THEN 'Death customs'
	WHEN LEFT(ddc, 3) = '394' THEN 'General customs'
	WHEN LEFT(ddc, 3) = '395' THEN 'Etiquette (Manners)'
	WHEN LEFT(ddc, 3) = '396' THEN 'Unassigned — formerly Women\'s position and treatment'
	WHEN LEFT(ddc, 3) = '397' THEN 'Unassigned — formerly outcast studies'
	WHEN LEFT(ddc, 3) = '398' THEN 'Folklore'
	WHEN LEFT(ddc, 3) = '399' THEN 'Customs of war and diplomacy'

	-- Language
	WHEN LEFT(ddc, 3) = '400' THEN 'Language'
	WHEN LEFT(ddc, 3) = '401' THEN 'Philosophy and theory, international languages'
	WHEN LEFT(ddc, 3) = '402' THEN 'Miscellany'
	WHEN LEFT(ddc, 3) = '403' THEN 'Dictionaries, encyclopedias, concordances'
	WHEN LEFT(ddc, 3) = '404' THEN 'Special topics of language'
	WHEN LEFT(ddc, 3) = '405' THEN 'Serial publications'
	WHEN LEFT(ddc, 3) = '406' THEN 'Organizations and management'
	WHEN LEFT(ddc, 3) = '407' THEN 'Education, research, related topics'
	WHEN LEFT(ddc, 3) = '408' THEN 'Groups of people'
	WHEN LEFT(ddc, 3) = '409' THEN 'Geographic treatment and biography'

	WHEN LEFT(ddc, 3) = '410' THEN 'Linguistics'
	WHEN LEFT(ddc, 3) = '411' THEN 'Writing systems of standard forms of languages'
	WHEN LEFT(ddc, 3) = '412' THEN 'Etymology of standard forms of languages'
	WHEN LEFT(ddc, 3) = '413' THEN 'Dictionaries of standard forms of languages'
	WHEN LEFT(ddc, 3) = '414' THEN 'Phonology and phonetics of standard forms of languages'
	WHEN LEFT(ddc, 3) = '415' THEN 'Grammar of standard forms of languages'
	WHEN LEFT(ddc, 3) = '416' THEN 'Unassigned — formerly Prosody'
	WHEN LEFT(ddc, 3) = '417' THEN 'Dialectology and historical linguistics'
	WHEN LEFT(ddc, 3) = '418' THEN 'Standard usage (Prescriptive linguistics)'
	WHEN LEFT(ddc, 3) = '419' THEN 'Sign languages'

	WHEN LEFT(ddc, 3) = '420' THEN 'English and Old English (Anglo-Saxon)'
	WHEN LEFT(ddc, 3) = '421' THEN 'Writing system, phonology, phonetics of standard English'
	WHEN LEFT(ddc, 3) = '422' THEN 'Etymology of standard English'
	WHEN LEFT(ddc, 3) = '423' THEN 'Dictionaries of standard English'
	WHEN LEFT(ddc, 3) = '424' THEN 'Unassigned — formerly English thesauruses'
	WHEN LEFT(ddc, 3) = '425' THEN 'Grammar of standard English'
	WHEN LEFT(ddc, 3) = '426' THEN 'Unassigned — formerly English prosodies'
	WHEN LEFT(ddc, 3) = '427' THEN 'Historical and geographical variations, modern nongeographic variations of English'
	WHEN LEFT(ddc, 3) = '428' THEN 'Standard English usage (Prescriptive linguistics)'
	WHEN LEFT(ddc, 3) = '429' THEN 'Old English (Anglo-Saxon)'

	WHEN LEFT(ddc, 3) = '430' THEN 'German and related languages'
	WHEN LEFT(ddc, 3) = '431' THEN 'Writing systems, phonology, phonetics of standard German'
	WHEN LEFT(ddc, 3) = '432' THEN 'Etymology of standard German'
	WHEN LEFT(ddc, 3) = '433' THEN 'Dictionaries of standard German'
	WHEN LEFT(ddc, 3) = '434' THEN 'Not assigned or Unassigned'
	WHEN LEFT(ddc, 3) = '435' THEN 'Grammar of standard German'
	WHEN LEFT(ddc, 3) = '436' THEN 'Unassigned 436'
	WHEN LEFT(ddc, 3) = '437' THEN 'Historical and geographic variations, modern nongeographic variations of German'
	WHEN LEFT(ddc, 3) = '438' THEN 'Standard German usage (Prescriptive linguistics)'
	WHEN LEFT(ddc, 3) = '439' THEN 'Other Germanic languages'
	
	WHEN LEFT(ddc, 3) = '440' THEN 'French and related Romance languages'
	WHEN LEFT(ddc, 3) = '441' THEN 'Writing systems, phonology, phonetics of standard French'
	WHEN LEFT(ddc, 3) = '442' THEN 'Etymology of standard French'
	WHEN LEFT(ddc, 3) = '443' THEN 'Dictionaries of standard French'
	WHEN LEFT(ddc, 3) = '444' THEN 'Unassigned 444'
	WHEN LEFT(ddc, 3) = '445' THEN 'Grammar of standard French'
	WHEN LEFT(ddc, 3) = '446' THEN 'Unassigned 446'
	WHEN LEFT(ddc, 3) = '447' THEN 'Historical and geographic variations, modern nongeographic variations of French'
	WHEN LEFT(ddc, 3) = '448' THEN 'Standard French usage (Prescriptive linguistics)'
	WHEN LEFT(ddc, 3) = '449' THEN 'Occitan Catalan, Franco-Provençal'

	WHEN LEFT(ddc, 3) = '450' THEN 'Italian, Dalmatian, Romanian, Rhaetian, Sardinian, Corsican'
	WHEN LEFT(ddc, 3) = '451' THEN 'Writing systems, phonology, phonetics of standard Italian'
	WHEN LEFT(ddc, 3) = '452' THEN 'Etymology of standard Italian'
	WHEN LEFT(ddc, 3) = '453' THEN 'Dictionaries of standard Italian'
	WHEN LEFT(ddc, 3) = '454' THEN 'Not assigned or Unassigned'
	WHEN LEFT(ddc, 3) = '455' THEN 'Grammar of standard Italian'
	WHEN LEFT(ddc, 3) = '456' THEN 'Unassigned 456'
	WHEN LEFT(ddc, 3) = '457' THEN 'Historical and geographic variations, modern nongeographic variations of Italian'
	WHEN LEFT(ddc, 3) = '458' THEN 'Standard Italian usage (Prescriptive linguistics)'
	WHEN LEFT(ddc, 3) = '459' THEN 'Romanian, Rhaetian, Sardinian, Corsican'

	WHEN LEFT(ddc, 3) = '460' THEN 'Spanish, Portuguese, Galician'
	WHEN LEFT(ddc, 3) = '461' THEN 'Writing systems, phonology, phonetics of standard Spanish'
	WHEN LEFT(ddc, 3) = '462' THEN 'Etymology of standard Spanish'
	WHEN LEFT(ddc, 3) = '463' THEN 'Dictionaries of standard Spanish'
	WHEN LEFT(ddc, 3) = '464' THEN 'Unassigned 464'
	WHEN LEFT(ddc, 3) = '465' THEN 'Grammar of standard Spanish'
	WHEN LEFT(ddc, 3) = '466' THEN 'Unassigned 466'
	WHEN LEFT(ddc, 3) = '467' THEN 'Historical and geographic variations, modern nongeographic variations of Spanish'
	WHEN LEFT(ddc, 3) = '468' THEN 'Standard Spanish usage (Prescriptive linguistics)'
	WHEN LEFT(ddc, 3) = '469' THEN 'Portuguese'

	WHEN LEFT(ddc, 3) = '470' THEN 'Latin and related Italic languages'
	WHEN LEFT(ddc, 3) = '471' THEN 'Writing systems, phonology, phonetics of classical Latin'
	WHEN LEFT(ddc, 3) = '472' THEN 'Etymology of classical Latin'
	WHEN LEFT(ddc, 3) = '473' THEN 'Dictionaries of classical Latin'
	WHEN LEFT(ddc, 3) = '474' THEN 'Unassigned'
	WHEN LEFT(ddc, 3) = '475' THEN 'Grammar of classical Latin'
	WHEN LEFT(ddc, 3) = '476' THEN 'Unassigned 476'
	WHEN LEFT(ddc, 3) = '477' THEN 'Old, postclassical, Vulgar Latin'
	WHEN LEFT(ddc, 3) = '478' THEN 'Classical Latin usage (Prescriptive linguistics)'
	WHEN LEFT(ddc, 3) = '479' THEN 'Other Italic languages'

	WHEN LEFT(ddc, 3) = '480' THEN 'Classical Greek and related Hellenic languages'
	WHEN LEFT(ddc, 3) = '481' THEN 'Writing systems, phonology, phonetics of classical Greek'
	WHEN LEFT(ddc, 3) = '482' THEN 'Etymology of classical Greek'
	WHEN LEFT(ddc, 3) = '483' THEN 'Dictionaries of classical Greek'
	WHEN LEFT(ddc, 3) = '484' THEN 'Unassigned'
	WHEN LEFT(ddc, 3) = '485' THEN 'Grammar of classical Greek'
	WHEN LEFT(ddc, 3) = '486' THEN 'Unassigned 486'
	WHEN LEFT(ddc, 3) = '487' THEN 'Preclassical and postclassical Greek'
	WHEN LEFT(ddc, 3) = '488' THEN 'Classical Greek usage (Prescriptive linguistics)'
	WHEN LEFT(ddc, 3) = '489' THEN 'Other Hellenic languages'

	WHEN LEFT(ddc, 3) = '490' THEN 'Other languages'
	WHEN LEFT(ddc, 3) = '491' THEN 'East Indo-European and Celtic languages'
	WHEN LEFT(ddc, 3) = '492' THEN 'Afro-Asiatic languages'
	WHEN LEFT(ddc, 3) = '493' THEN 'Non-Semitic Afro-Asiatic languages'
	WHEN LEFT(ddc, 3) = '494' THEN 'Altaic, Uralic, Hyperborean, Dravidian languages, miscellaneous languages of south Asia'
	WHEN LEFT(ddc, 3) = '495' THEN 'Languages of East and Southeast Asia'
	WHEN LEFT(ddc, 3) = '496' THEN 'African languages'
	WHEN LEFT(ddc, 3) = '497' THEN 'North American native languages'
	WHEN LEFT(ddc, 3) = '498' THEN 'South American native languages'
	WHEN LEFT(ddc, 3) = '499' THEN 'Non-Austronesian languages of Oceania, Austronesian languages, miscellaneous languages'

	-- Science
	WHEN LEFT(ddc, 3) = '500' THEN 'Natural sciences and mathematics'
	WHEN LEFT(ddc, 3) = '501' THEN 'Philosophy and theory'
	WHEN LEFT(ddc, 3) = '502' THEN 'Miscellany'
	WHEN LEFT(ddc, 3) = '503' THEN 'Dictionaries, encyclopedias, concordances'
	WHEN LEFT(ddc, 3) = '504' THEN 'Unassigned 504'
	WHEN LEFT(ddc, 3) = '505' THEN 'Serial publications'
	WHEN LEFT(ddc, 3) = '506' THEN 'Organizations and management'
	WHEN LEFT(ddc, 3) = '507' THEN 'Education, research, related topics'
	WHEN LEFT(ddc, 3) = '508' THEN 'Natural history'
	WHEN LEFT(ddc, 3) = '509' THEN 'History, geographic treatment, biography'

	WHEN LEFT(ddc, 3) = '510' THEN 'Mathematics'
	WHEN LEFT(ddc, 3) = '511' THEN 'General principles of mathematics'
	WHEN LEFT(ddc, 3) = '512' THEN 'Algebra'
	WHEN LEFT(ddc, 3) = '513' THEN 'Arithmetic'
	WHEN LEFT(ddc, 3) = '514' THEN 'Topology'
	WHEN LEFT(ddc, 3) = '515' THEN 'Analysis'
	WHEN LEFT(ddc, 3) = '516' THEN 'Geometry'
	WHEN LEFT(ddc, 3) = '517' THEN 'Unassigned 517'
	WHEN LEFT(ddc, 3) = '518' THEN 'Numerical analysis'
	WHEN LEFT(ddc, 3) = '519' THEN 'Probabilities and applied mathematics'

	WHEN LEFT(ddc, 3) = '520' THEN 'Astronomy and allied sciences'
	WHEN LEFT(ddc, 3) = '521' THEN 'Celestial mechanics'
	WHEN LEFT(ddc, 3) = '522' THEN 'Techniques, procedures, apparatus, equipment, materials'
	WHEN LEFT(ddc, 3) = '523' THEN 'Specific celestial bodies and phenomena'
	WHEN LEFT(ddc, 3) = '524' THEN 'Unassigned 524'
	WHEN LEFT(ddc, 3) = '525' THEN 'Earth (Astronomical geography)'
	WHEN LEFT(ddc, 3) = '526' THEN 'Mathematical geography'
	WHEN LEFT(ddc, 3) = '527' THEN 'Celestial navigation'
	WHEN LEFT(ddc, 3) = '528' THEN 'Ephemerides'
	WHEN LEFT(ddc, 3) = '529' THEN 'Chronology'

	WHEN LEFT(ddc, 3) = '530' THEN 'Physics'
	WHEN LEFT(ddc, 3) = '531' THEN 'Classical mechanics'
	WHEN LEFT(ddc, 3) = '532' THEN 'Fluid mechanics'
	WHEN LEFT(ddc, 3) = '533' THEN 'Pneumatics (Gas mechanics)'
	WHEN LEFT(ddc, 3) = '534' THEN 'Sound and related vibrations'
	WHEN LEFT(ddc, 3) = '535' THEN 'Light and related radiation'
	WHEN LEFT(ddc, 3) = '536' THEN 'Heat'
	WHEN LEFT(ddc, 3) = '537' THEN 'Electricity and electronics'
	WHEN LEFT(ddc, 3) = '538' THEN 'Magnetism'
	WHEN LEFT(ddc, 3) = '539' THEN 'Modern physics'

	WHEN LEFT(ddc, 3) = '540' THEN 'Chemistry and allied sciences'
	WHEN LEFT(ddc, 3) = '541' THEN 'Physical chemistry'
	WHEN LEFT(ddc, 3) = '542' THEN 'Techniques, procedures, apparatus, equipment, materials'
	WHEN LEFT(ddc, 3) = '543' THEN 'Analytical chemistry'
	WHEN LEFT(ddc, 3) = '544' THEN 'Unassigned — formerly Qualitative analysis'
	WHEN LEFT(ddc, 3) = '545' THEN 'Unassigned — formerly Quantitative analysis'
	WHEN LEFT(ddc, 3) = '546' THEN 'Inorganic chemistry'
	WHEN LEFT(ddc, 3) = '547' THEN 'Organic chemistry'
	WHEN LEFT(ddc, 3) = '548' THEN 'Crystallography'
	WHEN LEFT(ddc, 3) = '549' THEN 'Mineralogy'

	WHEN LEFT(ddc, 3) = '550' THEN 'Earth sciences'
	WHEN LEFT(ddc, 3) = '551' THEN 'Geology, hydrology, meteorology'
	WHEN LEFT(ddc, 3) = '552' THEN 'Petrology'
	WHEN LEFT(ddc, 3) = '553' THEN 'Economic geology'
	WHEN LEFT(ddc, 3) = '554' THEN 'Earth sciences of Europe'
	WHEN LEFT(ddc, 3) = '555' THEN 'Earth sciences of Asia'
	WHEN LEFT(ddc, 3) = '556' THEN 'Earth sciences of Africa'
	WHEN LEFT(ddc, 3) = '557' THEN 'Earth sciences of North America'
	WHEN LEFT(ddc, 3) = '558' THEN 'Earth sciences of South America'
	WHEN LEFT(ddc, 3) = '559' THEN 'Earth sciences of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds'

	WHEN LEFT(ddc, 3) = '560' THEN 'Paleontology'
	WHEN LEFT(ddc, 3) = '561' THEN 'Paleobotany, fossil microorganisms'
	WHEN LEFT(ddc, 3) = '562' THEN 'Fossil invertebrates'
	WHEN LEFT(ddc, 3) = '563' THEN 'Miscellaneous fossil marine and seashore invertebrates'
	WHEN LEFT(ddc, 3) = '564' THEN 'Fossil Mollusca and Molluscoidea'
	WHEN LEFT(ddc, 3) = '565' THEN 'Fossil Arthropoda'
	WHEN LEFT(ddc, 3) = '566' THEN 'Fossil Chordata'
	WHEN LEFT(ddc, 3) = '567' THEN 'Fossil cold-blooded vertebrates'
	WHEN LEFT(ddc, 3) = '568' THEN 'Fossil Aves (birds)'
	WHEN LEFT(ddc, 3) = '569' THEN 'Fossil Mammalia'

	WHEN LEFT(ddc, 3) = '570' THEN 'Biology'
	WHEN LEFT(ddc, 3) = '571' THEN 'Physiology and related subjects'
	WHEN LEFT(ddc, 3) = '572' THEN 'Biochemistry'
	WHEN LEFT(ddc, 3) = '573' THEN 'Specific physiological systems in animals, regional histology and physiology in animals'
	WHEN LEFT(ddc, 3) = '574' THEN 'Unassigned'
	WHEN LEFT(ddc, 3) = '575' THEN 'Specific parts of and physiological systems in plants'
	WHEN LEFT(ddc, 3) = '576' THEN 'Genetics and evolution'
	WHEN LEFT(ddc, 3) = '577' THEN 'Ecology'
	WHEN LEFT(ddc, 3) = '578' THEN 'Natural history of organisms and related subjects'
	WHEN LEFT(ddc, 3) = '579' THEN 'Natural history of microorganisms, fungi, algae'

	WHEN LEFT(ddc, 3) = '580' THEN 'Plants'
	WHEN LEFT(ddc, 3) = '581' THEN 'Specific topics in natural history of plants'
	WHEN LEFT(ddc, 3) = '582' THEN 'Plants noted for specific vegetative characteristics and flowers'
	WHEN LEFT(ddc, 3) = '583' THEN 'Magnoliopsida (Dicotyledones)'
	WHEN LEFT(ddc, 3) = '584' THEN 'Liliopsida (Monocotyledones)'
	WHEN LEFT(ddc, 3) = '585' THEN 'Pinophyta (Gymnosperms)'
	WHEN LEFT(ddc, 3) = '586' THEN 'Cryptogamia (Seedless plants)'
	WHEN LEFT(ddc, 3) = '587' THEN 'Pteridophyta'
	WHEN LEFT(ddc, 3) = '588' THEN 'Bryophyta'
	WHEN LEFT(ddc, 3) = '589' THEN 'Unassigned — formerly Forestry'

	WHEN LEFT(ddc, 3) = '590' THEN 'Animals'
	WHEN LEFT(ddc, 3) = '591' THEN 'Specific topics in natural history of animals'
	WHEN LEFT(ddc, 3) = '592' THEN 'Invertebrates'
	WHEN LEFT(ddc, 3) = '593' THEN 'Miscellaneous marine and seashore invertebrates'
	WHEN LEFT(ddc, 3) = '594' THEN 'Mollusca and Molluscoidea'
	WHEN LEFT(ddc, 3) = '595' THEN 'Arthropoda'
	WHEN LEFT(ddc, 3) = '596' THEN 'Chordata'
	WHEN LEFT(ddc, 3) = '597' THEN 'Cold-blooded vertebrates'
	WHEN LEFT(ddc, 3) = '598' THEN 'Aves (Birds)'
	WHEN LEFT(ddc, 3) = '599' THEN 'Mammalia (Mammals)'

	-- Technology
	WHEN LEFT(ddc, 3) = '600' THEN 'Technology (Applied sciences)'
	WHEN LEFT(ddc, 3) = '601' THEN 'Philosophy and theory'
	WHEN LEFT(ddc, 3) = '602' THEN 'Miscellany'
	WHEN LEFT(ddc, 3) = '603' THEN 'Dictionaries, encyclopedias, concordances'
	WHEN LEFT(ddc, 3) = '604' THEN 'Technical drawing, hazardous materials technology; groups of people'
	WHEN LEFT(ddc, 3) = '605' THEN 'Serial publications'
	WHEN LEFT(ddc, 3) = '606' THEN 'Organizations'
	WHEN LEFT(ddc, 3) = '607' THEN 'Education, research, related topics'
	WHEN LEFT(ddc, 3) = '608' THEN 'Patents'
	WHEN LEFT(ddc, 3) = '609' THEN 'History, geographic treatment, biography'
	
	WHEN LEFT(ddc, 3) = '610' THEN 'Medicine and health'
	WHEN LEFT(ddc, 3) = '611' THEN 'Human anatomy, cytology, histology'
	WHEN LEFT(ddc, 3) = '612' THEN 'Human physiology'
	WHEN LEFT(ddc, 3) = '613' THEN 'Personal health and safety'
	WHEN LEFT(ddc, 3) = '614' THEN 'Forensic medicine; incidence of injuries, wounds, disease; public preventive medicine'
	WHEN LEFT(ddc, 3) = '615' THEN 'Pharmacology and therapeutics'
	WHEN LEFT(ddc, 3) = '616' THEN 'Diseases'
	WHEN LEFT(ddc, 3) = '617' THEN 'Surgery, regional medicine, dentistry, ophthalmology, otology, audiology'
	WHEN LEFT(ddc, 3) = '618' THEN 'Gynecology, obstetrics, pediatrics, geriatrics'
	WHEN LEFT(ddc, 3) = '619' THEN 'Unassigned — formerly Experimental medicine'

	WHEN LEFT(ddc, 3) = '620' THEN 'Engineering and applied operations'
	WHEN LEFT(ddc, 3) = '621' THEN 'Applied physics'
	WHEN LEFT(ddc, 3) = '622' THEN 'Mining and related operations'
	WHEN LEFT(ddc, 3) = '623' THEN 'Military and nautical engineering'
	WHEN LEFT(ddc, 3) = '624' THEN 'Civil engineering'
	WHEN LEFT(ddc, 3) = '625' THEN 'Engineering of railroads, roads'
	WHEN LEFT(ddc, 3) = '626' THEN 'Unassigned'
	WHEN LEFT(ddc, 3) = '627' THEN 'Hydraulic engineering'
	WHEN LEFT(ddc, 3) = '628' THEN 'Sanitary engineering'
	WHEN LEFT(ddc, 3) = '629' THEN 'Other branches of engineering'

	WHEN LEFT(ddc, 3) = '630' THEN 'Agriculture and related technologies'
	WHEN LEFT(ddc, 3) = '631' THEN 'Specific techniques; apparatus, equipment, materials'
	WHEN LEFT(ddc, 3) = '632' THEN 'Plant injuries, diseases, pests'
	WHEN LEFT(ddc, 3) = '633' THEN 'Field and plantation crops'
	WHEN LEFT(ddc, 3) = '634' THEN 'Orchards, fruits, forestry'
	WHEN LEFT(ddc, 3) = '635' THEN 'Garden crops (Horticulture)'
	WHEN LEFT(ddc, 3) = '636' THEN 'Animal husbandry'
	WHEN LEFT(ddc, 3) = '637' THEN 'Processing dairy and related products'
	WHEN LEFT(ddc, 3) = '638' THEN 'Insect culture'
	WHEN LEFT(ddc, 3) = '639' THEN 'Hunting, fishing, conservation, related technologies'

	WHEN LEFT(ddc, 3) = '640' THEN 'Home and family management'
	WHEN LEFT(ddc, 3) = '641' THEN 'Food and drink'
	WHEN LEFT(ddc, 3) = '642' THEN 'Meals and table service'
	WHEN LEFT(ddc, 3) = '643' THEN 'Housing and household equipment'
	WHEN LEFT(ddc, 3) = '644' THEN 'Household utilities'
	WHEN LEFT(ddc, 3) = '645' THEN 'Household furnishings'
	WHEN LEFT(ddc, 3) = '646' THEN 'Sewing, clothing, management of personal and family life'
	WHEN LEFT(ddc, 3) = '647' THEN 'Management of public households (Institutional housekeeping)'
	WHEN LEFT(ddc, 3) = '648' THEN 'Housekeeping'
	WHEN LEFT(ddc, 3) = '649' THEN 'Child rearing; home care of people with disabilities and illnesses'
	
	WHEN LEFT(ddc, 3) = '650' THEN 'Management and auxiliary services'
	WHEN LEFT(ddc, 3) = '651' THEN 'Office services'
	WHEN LEFT(ddc, 3) = '652' THEN 'Processes of written communication'
	WHEN LEFT(ddc, 3) = '653' THEN 'Shorthand'
	WHEN LEFT(ddc, 3) BETWEEN '654' AND '656' THEN 'Unassigned (650s)'
	WHEN LEFT(ddc, 3) = '657' THEN 'Accounting'
	WHEN LEFT(ddc, 3) = '658' THEN 'General management'
	WHEN LEFT(ddc, 3) = '659' THEN 'Advertising and public relations'
	
	WHEN LEFT(ddc, 3) = '660' THEN 'Chemical engineering and related technologies'
	WHEN LEFT(ddc, 3) = '661' THEN 'Technology of industrial chemicals'
	WHEN LEFT(ddc, 3) = '662' THEN 'Technology of explosives, fuels, related products'
	WHEN LEFT(ddc, 3) = '663' THEN 'Beverage technology'
	WHEN LEFT(ddc, 3) = '664' THEN 'Food technology'
	WHEN LEFT(ddc, 3) = '665' THEN 'Technology of industrial oils, fats, waxes, gases'
	WHEN LEFT(ddc, 3) = '666' THEN 'Ceramic and allied technologies'
	WHEN LEFT(ddc, 3) = '667' THEN 'Cleaning, color, coating, related technologies'
	WHEN LEFT(ddc, 3) = '668' THEN 'Technology of other organic products'
	WHEN LEFT(ddc, 3) = '669' THEN 'Metallurgy'
	
	WHEN LEFT(ddc, 3) = '670' THEN 'Manufacturing'
	WHEN LEFT(ddc, 3) = '671' THEN 'Metalworking processes and primary metal products'
	WHEN LEFT(ddc, 3) = '672' THEN 'Iron, steel, other iron alloys'
	WHEN LEFT(ddc, 3) = '673' THEN 'Nonferrous metals'
	WHEN LEFT(ddc, 3) = '674' THEN 'Lumber processing, wood products, cork'
	WHEN LEFT(ddc, 3) = '675' THEN 'Leather and fur processing'
	WHEN LEFT(ddc, 3) = '676' THEN 'Pulp and paper technology'
	WHEN LEFT(ddc, 3) = '677' THEN 'Textiles'
	WHEN LEFT(ddc, 3) = '678' THEN 'Elastomers and elastomer products'
	WHEN LEFT(ddc, 3) = '679' THEN 'Other products of specific kinds of materials'

	WHEN LEFT(ddc, 3) = '680' THEN 'Manufacture of products for specific uses'
	WHEN LEFT(ddc, 3) = '681' THEN 'Precision instruments and other devices'
	WHEN LEFT(ddc, 3) = '682' THEN 'Small forge work (Blacksmithing)'
	WHEN LEFT(ddc, 3) = '683' THEN 'Hardware and household appliances'
	WHEN LEFT(ddc, 3) = '684' THEN 'Furnishings and home workshops'
	WHEN LEFT(ddc, 3) = '685' THEN 'Leather and fur goods, and related products'
	WHEN LEFT(ddc, 3) = '686' THEN 'Printing and related activities'
	WHEN LEFT(ddc, 3) = '687' THEN 'Clothing and accessories'
	WHEN LEFT(ddc, 3) = '688' THEN 'Other final products, and packaging technology'
	WHEN LEFT(ddc, 3) = '689' THEN 'Unassigned'

	WHEN LEFT(ddc, 3) = '690' THEN 'Construction of buildings'
	WHEN LEFT(ddc, 3) = '691' THEN 'Building materials'
	WHEN LEFT(ddc, 3) = '692' THEN 'Auxiliary construction practices'
	WHEN LEFT(ddc, 3) = '693' THEN 'Construction in specific types of materials and for specific purposes'
	WHEN LEFT(ddc, 3) = '694' THEN 'Wood construction'
	WHEN LEFT(ddc, 3) = '695' THEN 'Roof covering'
	WHEN LEFT(ddc, 3) = '696' THEN 'Utilities'
	WHEN LEFT(ddc, 3) = '697' THEN 'Heating, ventilating, air-conditioning engineering'
	WHEN LEFT(ddc, 3) = '698' THEN 'Detail finishing'
	WHEN LEFT(ddc, 3) = '699' THEN 'Unassigned 699'

	-- Arts and recreation
	
	WHEN LEFT(ddc, 3) = '700' THEN 'The Arts'
	WHEN LEFT(ddc, 3) = '701' THEN 'Philosophy and theory of fine and decorative arts'
	WHEN LEFT(ddc, 3) = '702' THEN 'Miscellany of fine and decorative arts'
	WHEN LEFT(ddc, 3) = '703' THEN 'Dictionaries, encyclopedias, concordances of fine and decorative arts'
	WHEN LEFT(ddc, 3) = '704' THEN 'Special topics in fine and decorative arts'
	WHEN LEFT(ddc, 3) = '705' THEN 'Serial publications of fine and decorative arts'
	WHEN LEFT(ddc, 3) = '706' THEN 'Organizations and management of fine and decorative arts'
	WHEN LEFT(ddc, 3) = '707' THEN 'Education, research, related topics of fine and decorative arts'
	WHEN LEFT(ddc, 3) = '708' THEN 'Galleries, museums, private collections of fine and decorative arts'
	WHEN LEFT(ddc, 3) = '709' THEN 'History, geographic treatment, biography'
	
	WHEN LEFT(ddc, 3) = '710' THEN 'Area planning and landscape architecture'
	WHEN LEFT(ddc, 3) = '711' THEN 'Area planning (Civic art)'
	WHEN LEFT(ddc, 3) = '712' THEN 'Landscape architecture (Landscape design)'
	WHEN LEFT(ddc, 3) = '713' THEN 'Landscape architecture of trafficways'
	WHEN LEFT(ddc, 3) = '714' THEN 'Water features in landscape architecture'
	WHEN LEFT(ddc, 3) = '715' THEN 'Woody plants in landscape architecture'
	WHEN LEFT(ddc, 3) = '716' THEN 'Herbaceous plants in landscape architecture'
	WHEN LEFT(ddc, 3) = '717' THEN 'Structures in landscape architecture'
	WHEN LEFT(ddc, 3) = '718' THEN 'Landscape design of cemeteries'
	WHEN LEFT(ddc, 3) = '719' THEN 'Natural landscapes'

	WHEN LEFT(ddc, 3) = '720' THEN 'Architecture'
	WHEN LEFT(ddc, 3) = '721' THEN 'Architectural materials and structural elements'
	WHEN LEFT(ddc, 3) = '722' THEN 'Architecture from earliest times to c. 300'
	WHEN LEFT(ddc, 3) = '723' THEN 'Architecture from c. 300 to 1399'
	WHEN LEFT(ddc, 3) = '724' THEN 'Architecture from c. 1400'
	WHEN LEFT(ddc, 3) = '725' THEN 'Public structures'
	WHEN LEFT(ddc, 3) = '726' THEN 'Buildings for religious and related purposes'
	WHEN LEFT(ddc, 3) = '727' THEN 'Buildings for educational and research purposes'
	WHEN LEFT(ddc, 3) = '728' THEN 'Residential and related buildings'
	WHEN LEFT(ddc, 3) = '729' THEN 'Design and decoration of structures and accessories'

	WHEN LEFT(ddc, 3) = '730' THEN 'Sculpture and related arts'
	WHEN LEFT(ddc, 3) = '731' THEN 'Processes, forms, subjects of sculpture'
	WHEN LEFT(ddc, 3) = '732' THEN 'Sculpture from earliest times to c. 500, sculpture of non-literate peoples'
	WHEN LEFT(ddc, 3) = '733' THEN 'Greek, Etruscan, Roman sculpture'
	WHEN LEFT(ddc, 3) = '734' THEN 'Sculpture from ca 500 to 1399'
	WHEN LEFT(ddc, 3) = '735' THEN 'Sculpture from 1400'
	WHEN LEFT(ddc, 3) = '736' THEN 'Carving and carvings'
	WHEN LEFT(ddc, 3) = '737' THEN 'Numismatics and sigillography'
	WHEN LEFT(ddc, 3) = '738' THEN 'Ceramic arts'
	WHEN LEFT(ddc, 3) = '739' THEN 'Art metalwork'

	WHEN LEFT(ddc, 3) = '740' THEN 'Graphic arts'
	WHEN LEFT(ddc, 3) = '741' THEN 'Drawing and drawings'
	WHEN LEFT(ddc, 3) = '742' THEN 'Perspective in drawing'
	WHEN LEFT(ddc, 3) = '743' THEN 'Drawing and drawings by subject'
	WHEN LEFT(ddc, 3) = '744' THEN 'Communication design and visual design (proposed[5])'
	WHEN LEFT(ddc, 3) = '745' THEN 'Decorative arts'
	WHEN LEFT(ddc, 3) = '746' THEN 'Textile arts'
	WHEN LEFT(ddc, 3) = '747' THEN 'Interior decoration'
	WHEN LEFT(ddc, 3) = '748' THEN 'Glass'
	WHEN LEFT(ddc, 3) = '749' THEN 'Furniture and accessories'

	WHEN LEFT(ddc, 3) = '750' THEN 'Painting and paintings'
	WHEN LEFT(ddc, 3) = '751' THEN 'Techniques, procedures, apparatus, equipment, materials, forms'
	WHEN LEFT(ddc, 3) = '752' THEN 'Color'
	WHEN LEFT(ddc, 3) = '753' THEN 'Symbolism, allegory, mythology, legend'
	WHEN LEFT(ddc, 3) = '754' THEN 'Genre paintings'
	WHEN LEFT(ddc, 3) = '755' THEN 'Religion'
	WHEN LEFT(ddc, 3) = '756' THEN 'Unassigned 756'
	WHEN LEFT(ddc, 3) = '757' THEN 'Human figures'
	WHEN LEFT(ddc, 3) = '758' THEN 'Nature, architectural subjects and cityscapes, other specific subjects'
	WHEN LEFT(ddc, 3) = '759' THEN 'History, geographic treatment, biography'

	WHEN LEFT(ddc, 3) = '760' THEN 'Printmaking and prints'
	WHEN LEFT(ddc, 3) = '761' THEN 'Relief processes (Block printing)'
	WHEN LEFT(ddc, 3) = '762' THEN 'Unassigned 762'
	WHEN LEFT(ddc, 3) = '763' THEN 'Lithographic processes (Planographic processes)'
	WHEN LEFT(ddc, 3) = '764' THEN 'Chromolithography and serigraphy'
	WHEN LEFT(ddc, 3) = '765' THEN 'Metal engraving'
	WHEN LEFT(ddc, 3) = '766' THEN 'Mezzotinting, aquatinting, and related processes'
	WHEN LEFT(ddc, 3) = '767' THEN 'Etching and drypoint'
	WHEN LEFT(ddc, 3) = '768' THEN 'Unassigned 768'
	WHEN LEFT(ddc, 3) = '769' THEN 'Prints'

	WHEN LEFT(ddc, 3) = '770' THEN 'Photography, computer art, cinematography, videography'
	WHEN LEFT(ddc, 3) = '771' THEN 'Techniques, procedures, apparatus, equipment, materials'
	WHEN LEFT(ddc, 3) = '772' THEN 'Metallic salt processes'
	WHEN LEFT(ddc, 3) = '773' THEN 'Pigment processes of printing'
	WHEN LEFT(ddc, 3) = '774' THEN 'Unassigned - formerly Holography'
	WHEN LEFT(ddc, 3) = '775' THEN 'Unassigned - formerly Digital photography'
	WHEN LEFT(ddc, 3) = '776' THEN 'Computer art (Digital art)'
	WHEN LEFT(ddc, 3) = '777' THEN 'Cinematography and Videography'
	WHEN LEFT(ddc, 3) = '778' THEN 'Specific fields and special kinds of photography'
	WHEN LEFT(ddc, 3) = '779' THEN 'Photographic images'

	WHEN LEFT(ddc, 3) = '780' THEN 'Music'
	WHEN LEFT(ddc, 3) = '781' THEN 'General principles and musical forms'
	WHEN LEFT(ddc, 3) = '782' THEN 'Vocal music'
	WHEN LEFT(ddc, 3) = '783' THEN 'Music for single voices'
	WHEN LEFT(ddc, 3) = '784' THEN 'Instruments and Instrumental ensembles and their music'
	WHEN LEFT(ddc, 3) = '785' THEN 'Ensembles with only one instrument per part'
	WHEN LEFT(ddc, 3) = '786' THEN 'Keyboard, mechanical, electrophonic, percussion instruments'
	WHEN LEFT(ddc, 3) = '787' THEN 'Stringed instruments (Chordophones)'
	WHEN LEFT(ddc, 3) = '788' THEN 'Wind instruments (Aerophones)'
	WHEN LEFT(ddc, 3) = '789' THEN 'Unassigned 789'

	WHEN LEFT(ddc, 3) = '790' THEN 'Recreational and performing arts'
	WHEN LEFT(ddc, 3) = '791' THEN 'Public performances'
	WHEN LEFT(ddc, 3) = '792' THEN 'Stage presentations'
	WHEN LEFT(ddc, 3) = '793' THEN 'Indoor games and amusements'
	WHEN LEFT(ddc, 3) = '794' THEN 'Indoor games of skill'
	WHEN LEFT(ddc, 3) = '795' THEN 'Games of chance'
	WHEN LEFT(ddc, 3) = '796' THEN 'Athletic and outdoor sports and games'
	WHEN LEFT(ddc, 3) = '797' THEN 'Aquatic and air sports'
	WHEN LEFT(ddc, 3) = '798' THEN 'Equestrian sports and animal racing'
	WHEN LEFT(ddc, 3) = '799' THEN 'Fishing, hunting, shooting'

	-- Literature
	
	WHEN LEFT(ddc, 3) = '800' THEN 'Literature (Belles-lettres) and rhetoric'
	WHEN LEFT(ddc, 3) = '801' THEN 'Philosophy and theory'
	WHEN LEFT(ddc, 3) = '802' THEN 'Miscellany'
	WHEN LEFT(ddc, 3) = '803' THEN 'Dictionaries, encyclopedias, concordances'
	WHEN LEFT(ddc, 3) = '804' THEN 'Unassigned 804'
	WHEN LEFT(ddc, 3) = '805' THEN 'Serial publications'
	WHEN LEFT(ddc, 3) = '806' THEN 'Organizations and management'
	WHEN LEFT(ddc, 3) = '807' THEN 'Education, research, related topics'
	WHEN LEFT(ddc, 3) = '808' THEN 'Rhetoric and collections of literary texts from more than two literatures'
	WHEN LEFT(ddc, 3) = '809' THEN 'History, description, critical appraisal of more than two literatures'
		
	WHEN LEFT(ddc, 3) = '810' THEN 'American literature in English'
	WHEN LEFT(ddc, 3) = '811' THEN 'American poetry in English'
	WHEN LEFT(ddc, 3) = '812' THEN 'American drama in English'
	WHEN LEFT(ddc, 3) = '813' THEN 'American fiction in English'
	WHEN LEFT(ddc, 3) = '814' THEN 'American essays in English'
	WHEN LEFT(ddc, 3) = '815' THEN 'American speeches in English'
	WHEN LEFT(ddc, 3) = '816' THEN 'American letters in English'
	WHEN LEFT(ddc, 3) = '817' THEN 'American humor and satire in English'
	WHEN LEFT(ddc, 3) = '818' THEN 'American miscellaneous writings in English'
	WHEN LEFT(ddc, 3) = '819' THEN 'Unassigned 819 - formerly Puzzle activities'

	WHEN LEFT(ddc, 3) = '820' THEN 'English and Old English (Anglo-Saxon) literatures'
	WHEN LEFT(ddc, 3) = '821' THEN 'English poetry'
	WHEN LEFT(ddc, 3) = '822' THEN 'English drama'
	WHEN LEFT(ddc, 3) = '823' THEN 'English fiction'
	WHEN LEFT(ddc, 3) = '824' THEN 'English essays'
	WHEN LEFT(ddc, 3) = '825' THEN 'English speeches'
	WHEN LEFT(ddc, 3) = '826' THEN 'English letters'
	WHEN LEFT(ddc, 3) = '827' THEN 'English humor and satire'
	WHEN LEFT(ddc, 3) = '828' THEN 'English miscellaneous writings'
	WHEN LEFT(ddc, 3) = '829' THEN 'Old English (Anglo-Saxon) literature'

	WHEN LEFT(ddc, 3) = '830' THEN 'German literature and literatures of related languages'
	WHEN LEFT(ddc, 3) = '831' THEN 'German poetry'
	WHEN LEFT(ddc, 3) = '832' THEN 'German drama'
	WHEN LEFT(ddc, 3) = '833' THEN 'German fiction'
	WHEN LEFT(ddc, 3) = '834' THEN 'German essays'
	WHEN LEFT(ddc, 3) = '835' THEN 'German speeches'
	WHEN LEFT(ddc, 3) = '836' THEN 'German letters'
	WHEN LEFT(ddc, 3) = '837' THEN 'German humor and satire'
	WHEN LEFT(ddc, 3) = '838' THEN 'German miscellaneous writings'
	WHEN LEFT(ddc, 3) = '839' THEN 'Other Germanic literatures'

	WHEN LEFT(ddc, 3) = '840' THEN 'French literature and literatures of related Romance languages'
	WHEN LEFT(ddc, 3) = '841' THEN 'French poetry'
	WHEN LEFT(ddc, 3) = '842' THEN 'French drama'
	WHEN LEFT(ddc, 3) = '843' THEN 'French fiction'
	WHEN LEFT(ddc, 3) = '844' THEN 'French essays'
	WHEN LEFT(ddc, 3) = '845' THEN 'French speeches'
	WHEN LEFT(ddc, 3) = '846' THEN 'French letters'
	WHEN LEFT(ddc, 3) = '847' THEN 'French humor and satire'
	WHEN LEFT(ddc, 3) = '848' THEN 'French miscellaneous writings'
	WHEN LEFT(ddc, 3) = '849' THEN 'Occitan, Catalan, Franco-Provençal literatures'
	
	WHEN LEFT(ddc, 3) = '850' THEN 'Literatures of Italian, Dalmatian, Romanian, Rhaetian, Sardinian, Corsican languages'
	WHEN LEFT(ddc, 3) = '851' THEN 'Italian poetry'
	WHEN LEFT(ddc, 3) = '852' THEN 'Italian drama'
	WHEN LEFT(ddc, 3) = '853' THEN 'Italian fiction'
	WHEN LEFT(ddc, 3) = '854' THEN 'Italian essays'
	WHEN LEFT(ddc, 3) = '855' THEN 'Italian speeches'
	WHEN LEFT(ddc, 3) = '856' THEN 'Italian letters'
	WHEN LEFT(ddc, 3) = '857' THEN 'Italian humor and satire'
	WHEN LEFT(ddc, 3) = '858' THEN 'Italian miscellaneous writings'
	WHEN LEFT(ddc, 3) = '859' THEN 'Literatures of Romanian, Rhaetian, Sardinian, Corsican languages'

	WHEN LEFT(ddc, 3) = '860' THEN 'Literatures of Spanish, Portuguese, Galician languages'
	WHEN LEFT(ddc, 3) = '861' THEN 'Spanish poetry'
	WHEN LEFT(ddc, 3) = '862' THEN 'Spanish drama'
	WHEN LEFT(ddc, 3) = '863' THEN 'Spanish fiction'
	WHEN LEFT(ddc, 3) = '864' THEN 'Spanish essays'
	WHEN LEFT(ddc, 3) = '865' THEN 'Spanish speeches'
	WHEN LEFT(ddc, 3) = '866' THEN 'Spanish letters'
	WHEN LEFT(ddc, 3) = '867' THEN 'Spanish humor and satire'
	WHEN LEFT(ddc, 3) = '868' THEN 'Spanish miscellaneous writings'
	WHEN LEFT(ddc, 3) = '869' THEN 'Literatures of Portuguese and Galician languages'

	WHEN LEFT(ddc, 3) = '870' THEN 'Latin literature and literatures of related Italic languages'
	WHEN LEFT(ddc, 3) = '871' THEN 'Latin poetry'
	WHEN LEFT(ddc, 3) = '872' THEN 'Latin dramatic poetry and drama'
	WHEN LEFT(ddc, 3) = '873' THEN 'Latin epic poetry and fiction'
	WHEN LEFT(ddc, 3) = '874' THEN 'Latin lyric poetry'
	WHEN LEFT(ddc, 3) = '875' THEN 'Latin speeches'
	WHEN LEFT(ddc, 3) = '876' THEN 'Latin letters'
	WHEN LEFT(ddc, 3) = '877' THEN 'Latin humor and satire'
	WHEN LEFT(ddc, 3) = '878' THEN 'Latin miscellaneous writings'
	WHEN LEFT(ddc, 3) = '879' THEN 'Literatures of other Italic languages'

	WHEN LEFT(ddc, 3) = '880' THEN 'Classical Greek literature and literatures of related Hellenic languages'
	WHEN LEFT(ddc, 3) = '881' THEN 'Classical Greek poetry'
	WHEN LEFT(ddc, 3) = '882' THEN 'Classical Greek drama'
	WHEN LEFT(ddc, 3) = '883' THEN 'Classical Greek epic poetry and fiction'
	WHEN LEFT(ddc, 3) = '884' THEN 'Classical Greek lyric poetry'
	WHEN LEFT(ddc, 3) = '885' THEN 'Classical Greek speeches'
	WHEN LEFT(ddc, 3) = '886' THEN 'Classical Greek letters'
	WHEN LEFT(ddc, 3) = '887' THEN 'Classical Greek humor and satire'
	WHEN LEFT(ddc, 3) = '888' THEN 'Classical Greek miscellaneous writings'
	WHEN LEFT(ddc, 3) = '889' THEN 'Modern Greek literature'

	WHEN LEFT(ddc, 3) = '890' THEN 'Literatures of other specific languages and language families'
	WHEN LEFT(ddc, 3) = '891' THEN 'East Indo-European and Celtic literatures'
	WHEN LEFT(ddc, 3) = '892' THEN 'Afro-Asiatic literatures'
	WHEN LEFT(ddc, 3) = '893' THEN 'Non-Semitic Afro-Asiatic literatures'
	WHEN LEFT(ddc, 3) = '894' THEN 'Literatures of Altaic, Uralic, Hyperborean, Dravidian languages; literatures of miscellaneous languages of South Asia'
	WHEN LEFT(ddc, 3) = '895' THEN 'Literatures of East and Southeast Asia'
	WHEN LEFT(ddc, 3) = '896' THEN 'African literatures'
	WHEN LEFT(ddc, 3) = '897' THEN 'Literatures of North American native languages'
	WHEN LEFT(ddc, 3) = '898' THEN 'Literatures of South American native languages'
	WHEN LEFT(ddc, 3) = '899' THEN 'Literatures of non-Austronesian languages of Oceania, of Austronesian languages, of miscellaneous languages'

	-- History and Geography
	WHEN LEFT(ddc, 3) = '900' THEN 'History, geography, and auxiliary disciplines'
	WHEN LEFT(ddc, 3) = '901' THEN 'Philosophy and theory of history'
	WHEN LEFT(ddc, 3) = '902' THEN 'Miscellany of history'
	WHEN LEFT(ddc, 3) = '903' THEN 'Dictionaries, encyclopedias, concordances of history'
	WHEN LEFT(ddc, 3) = '904' THEN 'Collected accounts of events'
	WHEN LEFT(ddc, 3) = '905' THEN 'Serial publications of history'
	WHEN LEFT(ddc, 3) = '906' THEN 'Organizations and management of history'
	WHEN LEFT(ddc, 3) = '907' THEN 'Education, research, related topics of history'
	WHEN LEFT(ddc, 3) = '908' THEN 'History with respect to groups of people'
	WHEN LEFT(ddc, 3) = '909' THEN 'World history'

	WHEN LEFT(ddc, 3) = '910' THEN 'Geography and travel'
	WHEN LEFT(ddc, 3) = '911' THEN 'Historical geography'
	WHEN LEFT(ddc, 3) = '912' THEN 'Graphic representations of surface of Earth and of extraterrestrial worlds'
	WHEN LEFT(ddc, 3) = '913' THEN 'Geography of and travel in the ancient world'
	WHEN LEFT(ddc, 3) = '914' THEN 'Geography of and travel in Europe'
	WHEN LEFT(ddc, 3) = '915' THEN 'Geography of and travel in Asia'
	WHEN LEFT(ddc, 3) = '916' THEN 'Geography of and travel in Africa'
	WHEN LEFT(ddc, 3) = '917' THEN 'Geography of and travel in North America'
	WHEN LEFT(ddc, 3) = '918' THEN 'Geography of and travel in South America'
	WHEN LEFT(ddc, 3) = '919' THEN 'Geography of and travel in Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica. extraterrestrial worlds'

	WHEN LEFT(ddc, 3) = '920' THEN 'Biography, genealogy, insignia'
	WHEN LEFT(ddc, 3) BETWEEN '921' AND '928' THEN 'Reserved location for biographies'
	WHEN LEFT(ddc, 3) = '929' THEN 'Genealogy, names, insignia'

	WHEN LEFT(ddc, 3) = '930' THEN 'History of ancient world to c. 499'
	WHEN LEFT(ddc, 3) = '931' THEN 'China to 420'
	WHEN LEFT(ddc, 3) = '932' THEN 'Egypt to 640'
	WHEN LEFT(ddc, 3) = '933' THEN 'Palestine to 70'
	WHEN LEFT(ddc, 3) = '934' THEN 'South Asia to 647'
	WHEN LEFT(ddc, 3) = '935' THEN 'Mesopotamia and Iranian Plateau to 637'
	WHEN LEFT(ddc, 3) = '936' THEN 'Europe north and west of Italian Peninsula to c. 499'
	WHEN LEFT(ddc, 3) = '937' THEN 'Italy and adjacent territories to 476'
	WHEN LEFT(ddc, 3) = '938' THEN 'Greece to 323'
	WHEN LEFT(ddc, 3) = '939' THEN 'Other parts of ancient world'

	WHEN LEFT(ddc, 3) = '940' THEN 'History of Europe'
	WHEN LEFT(ddc, 3) = '941' THEN 'British Isles'
	WHEN LEFT(ddc, 3) = '942' THEN 'England and Wales'
	WHEN LEFT(ddc, 3) = '943' THEN 'Germany and neighboring central European countries'
	WHEN LEFT(ddc, 3) = '944' THEN 'France and Monaco'
	WHEN LEFT(ddc, 3) = '945' THEN 'Italy, San Marino, Vatican City, Malta'
	WHEN LEFT(ddc, 3) = '946' THEN 'Spain, Andorra, Gibraltar, Portugal'
	WHEN LEFT(ddc, 3) = '947' THEN 'Russia and neighboring east European countries'
	WHEN LEFT(ddc, 3) = '948' THEN 'Scandinavia'
	WHEN LEFT(ddc, 3) = '949' THEN 'Other parts of Europe'

	WHEN LEFT(ddc, 3) = '950' THEN 'History of Asia'
	WHEN LEFT(ddc, 3) = '951' THEN 'China and adjacent areas'
	WHEN LEFT(ddc, 3) = '952' THEN 'Japan'
	WHEN LEFT(ddc, 3) = '953' THEN 'Arabian Peninsula and adjacent areas'
	WHEN LEFT(ddc, 3) = '954' THEN 'India and neighboring south Asian countries'
	WHEN LEFT(ddc, 3) = '955' THEN 'Iran'
	WHEN LEFT(ddc, 3) = '956' THEN 'Middle East (Near East)'
	WHEN LEFT(ddc, 3) = '957' THEN 'Siberia (Asiatic Russia)'
	WHEN LEFT(ddc, 3) = '958' THEN 'Central Asia'
	WHEN LEFT(ddc, 3) = '959' THEN 'Southeast Asia'

	WHEN LEFT(ddc, 3) = '960' THEN 'History of Africa'
	WHEN LEFT(ddc, 3) = '961' THEN 'Tunisia and Libya'
	WHEN LEFT(ddc, 3) = '962' THEN 'Egypt, Sudan, South Sudan'
	WHEN LEFT(ddc, 3) = '963' THEN 'Ethiopia and Eritrea'
	WHEN LEFT(ddc, 3) = '964' THEN 'Morocco, Ceuta, Melilla Western Sahara, Canary Islands'
	WHEN LEFT(ddc, 3) = '965' THEN 'Algeria'
	WHEN LEFT(ddc, 3) = '966' THEN 'West Africa and offshore islands'
	WHEN LEFT(ddc, 3) = '967' THEN 'Central Africa and offshore islands'
	WHEN LEFT(ddc, 3) = '968' THEN 'South Africa & southern Africa'
	WHEN LEFT(ddc, 3) = '969' THEN 'South Indian Ocean islands'

	WHEN LEFT(ddc, 3) = '970' THEN 'History of North America'
	WHEN LEFT(ddc, 3) = '971' THEN 'Canada'
	WHEN LEFT(ddc, 3) = '972' THEN 'Mexico, Central America, West Indies, Bermuda'
	WHEN LEFT(ddc, 3) = '973' THEN 'United States'
	WHEN LEFT(ddc, 3) = '974' THEN 'Northeastern United States (New England and Middle Atlantic states)'
	WHEN LEFT(ddc, 3) = '975' THEN 'Southeastern United States (South Atlantic states)'
	WHEN LEFT(ddc, 3) = '976' THEN 'South central United States'
	WHEN LEFT(ddc, 3) = '977' THEN 'North central United States'
	WHEN LEFT(ddc, 3) = '978' THEN 'Western United States'
	WHEN LEFT(ddc, 3) = '979' THEN 'Great Basin and Pacific Slope region of United States'

	WHEN LEFT(ddc, 3) = '980' THEN 'History of South America'
	WHEN LEFT(ddc, 3) = '981' THEN 'Brazil'
	WHEN LEFT(ddc, 3) = '982' THEN 'Argentina'
	WHEN LEFT(ddc, 3) = '983' THEN 'Chile'
	WHEN LEFT(ddc, 3) = '984' THEN 'Bolivia'
	WHEN LEFT(ddc, 3) = '985' THEN 'Peru'
	WHEN LEFT(ddc, 3) = '986' THEN 'Colombia and Ecuador'
	WHEN LEFT(ddc, 3) = '987' THEN 'Venezuela'
	WHEN LEFT(ddc, 3) = '988' THEN 'Guiana'
	WHEN LEFT(ddc, 3) = '989' THEN 'Paraguay and Uruguay'

	WHEN LEFT(ddc, 3) = '990' THEN 'History of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds'
	WHEN LEFT(ddc, 3) BETWEEN '991' AND '992' THEN 'Unassigned (990s)'
	WHEN LEFT(ddc, 3) = '993' THEN 'New Zealand'
	WHEN LEFT(ddc, 3) = '994' THEN 'Australia'
	WHEN LEFT(ddc, 3) = '995' THEN 'New Guinea and neighboring countries of Melanesia'
	WHEN LEFT(ddc, 3) = '996' THEN 'Polynesia and other Pacific Ocean islands'
	WHEN LEFT(ddc, 3) = '997' THEN 'Atlantic Ocean islands'
	WHEN LEFT(ddc, 3) = '998' THEN 'Arctic islands and Antarctica'
	WHEN LEFT(ddc, 3) = '999' THEN 'Extraterrestrial worlds'

  ELSE 'Unclassified'
END
WHERE ddc REGEXP '^[0-9]{1,3}(\\.[0-9]+)?$';

";

